baseurl = "https://example.com"
defaultContentLanguage = "zh"
languageCode = "zh-Hans"
title = "xiestr's blog"
theme = "dream"
hasCJKLanguage = true

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "business"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

author = "xiestr"
description = "小谢的时光记录~"
avatar = "img/avatar.jpg"
headerTitle = "xiestr"
# 座右铭
# motto = ""

# footerBottomText = ""

rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "kilzo_zh@outlook.com"

siteStartYear = 2025

favicon = "favicon.jpg"

# options
stickyNav = true
reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
showTableOfContents = true
showPrevNextPost = true
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
# reorderShares = ["x", "facebook", "whatsapp"]
showRandomSummaryCoverFromWeb = false


# Syntax highlighting
customSyntaxHighlighting = true

[markup]
[markup.highlight]
  anchorLineNos = true
  guessSyntax = true
  codeFences = true
  noClasses = false
[markup.tableOfContents]
  endLevel = 5
  ordered = false
  startLevel = 2
# [params.navItems]

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

[params.advanced]
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"